"""Verify the QR code generated by pdf_generator.py decodes to the
expected Calendly URL.

Generates a fresh QR PNG (same code path the PDF uses), then decodes it
with pyzbar and prints PASS/FAIL.
"""

import io
import sys
from pathlib import Path

from PIL import Image
from pyzbar.pyzbar import decode

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import pdf_generator  # noqa: E402


def main():
    expected = pdf_generator.CALENDLY_URL
    png_bytes = pdf_generator.generate_qr_png_bytes(expected)
    img = Image.open(io.BytesIO(png_bytes))
    decoded = decode(img)
    if not decoded:
        print(f"FAIL: pyzbar could not decode the QR PNG")
        sys.exit(1)
    actual = decoded[0].data.decode("utf-8")
    print(f"Expected: {expected}")
    print(f"Decoded:  {actual}")
    if actual == expected:
        print(f"PASS: QR decodes to {pdf_generator.REP_NAME}'s Calendly URL")
        sys.exit(0)
    print("FAIL: QR contents do not match expected URL")
    sys.exit(1)


if __name__ == "__main__":
    main()
